"""Shared HTML email theming and branding (AtLongLast Analytics)."""

from __future__ import annotations

import datetime as dt

BRAND = "AtLongLast Analytics"
TAGLINE = "Private Data & AI Engineering"
SITE = "atlonglastanalytics.com"

_HEADER = "#000000"
_ACCENT = "#2f6fb0"
_INK = "#1f2937"
_MUTED = "#6b7280"
_LINE = "#e5e7eb"
_UP = "#b91c1c"  # a cost increase — worth attention
_DOWN = "#047857"  # a cost decrease — good news


def delta_html(pct: float) -> str:
    """Render a percentage change, coloured by direction.

    Increases are red (the direction to watch on a cost tool) and decreases
    green, so the movers that matter stand out at a glance.
    """
    color = _UP if pct > 0 else _DOWN if pct < 0 else _MUTED
    return f"<span style='color:{color};font-weight:600'>{pct:+.1f}%</span>"


def wrap_email(title: str, body_html: str) -> str:
    """Wrap body content in a branded, standalone HTML email document."""
    stamp = dt.datetime.now(dt.UTC).strftime("%d %b %Y %H:%M UTC")
    header = (
        f"<div style='background:{_HEADER};color:#ffffff;padding:20px 24px'>"
        "<div style='font-size:12px;letter-spacing:2px;"
        f"text-transform:uppercase;opacity:0.8'>{BRAND}</div>"
        f"<div style='font-size:22px;font-weight:600;margin-top:2px'>{title}</div>"
        f"<div style='font-size:12px;opacity:0.75;margin-top:4px'>{TAGLINE}</div>"
        "</div>"
    )
    footer = (
        f"<hr style='border:none;border-top:1px solid {_LINE};margin:24px 0'>"
        f"<div style='font-size:12px;color:{_MUTED}'>"
        f"Generated by {BRAND} &middot; {stamp} &middot; "
        f"<a href='https://{SITE}' style='color:{_ACCENT};text-decoration:none'>{SITE}</a>"
        "</div>"
    )
    return (
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'></head>"
        f"<body style='margin:0;padding:24px 0;background:#f3f4f6;color:{_INK};"
        "font-family:Segoe UI,Arial,sans-serif'>"
        "<div style='max-width:640px;margin:0 auto;background:#ffffff;"
        f"border:1px solid {_LINE};border-radius:10px;overflow:hidden'>"
        f"{header}<div style='padding:24px'>{body_html}{footer}</div>"
        "</div></body></html>"
    )


def table(headers: list[str], rows: list[list[str]]) -> str:
    """Render a styled HTML table from headers and string rows."""
    head = "".join(
        f"<th style='text-align:left;padding:8px;border-bottom:2px solid {_LINE}'>{h}</th>"
        for h in headers
    )
    body = ""
    last = len(rows) - 1
    for index, row in enumerate(rows):
        border = "" if index == last else f"border-bottom:1px solid {_LINE}"
        cells = "".join(f"<td style='padding:8px;{border}'>{cell}</td>" for cell in row)
        body += f"<tr>{cells}</tr>"
    return (
        "<table style='width:100%;border-collapse:collapse;font-size:14px'>"
        f"<tr>{head}</tr>{body}</table>"
    )
